<?php
define('COOKIE_FILE_PATH', '../cache');
include('../functions.php');
$pageId = 2;
include('whitehousepetition.php');
$description = '<p>Concerns regarding vaccinations continue to increase exponentially in light of all of the information and documentation that has surfaced over the past few years. As a result, corporate media has responded to alternative media, stating that the increase of persons who are choosing to opt out of vaccines and the recommended vaccine schedule is a result of ‘fear mongering.’

This may not be too surprising as the corporate media is owned by the major vaccine manufacturers, and the major vaccine manufacturers are owned by corporate media(1)(2)(3)(4). Given this fact, it’s easy to fathom the possibility that these institutions are desperately trying to protect the reputation of their product.

For example, if we take a look at GlaxoSmithKline and Pfizer, they are owned by the same financial institutions and groups that own Time Warner (CNN, HBO etc.) and General Electric (NBC, Comcast, Universal Pictures etc.).(1)(2)(3)(4) This is seen throughout all of the major vaccine manufacturers and all of the 6 corporations that control our mainstream media. Keep in mind that these are the major funders of all ‘medical research’ that’s used to administer drugs and vaccinations. Despite these connections, medical research and documentation exists to show that vaccines might indeed be a cause for concern.</p>
';
$img = 'https://socioecohistory.files.wordpress.com/2014/03/vaccines_n_autism.png?w=500&h=360';
$title = '22 Medical Studies That Show Vaccines Can Cause Autism';
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta property="og:type" content="website" />
<meta property="og:url" content="http://<?php echo $_SERVER['HTTP_HOST']; ?><?php echo $_SERVER['REQUEST_URI']; ?>" />
<meta property="og:description" content="<?php echo $description; ?>" />
<meta property="og:image" content="<?php echo $img; ?>" />
<meta property="og:title" content="<?php echo $title; ?>" />
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Homeopathy And Vaccinations</title>

    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">

<style type="text/css">
body {
 padding-top: 50px; 
}
</style>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Homeopathy</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/news/">Home</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <h1><?php echo $title; ?></h1>
        <h2>Vaccines and Autism, Both Sides of The Coin</h2>
        <p>Here we will simply present information from both sides of the coin because many are not even aware that two sides exist. We&rsquo;ve presented multiple studies, citing multiple research papers and published research conducted by doctors and universities from all across the world. <a href="http://www.ecomed.org.uk/wp-content/uploads/2011/09/3-tomljenovic.pdf" onclick="javascript:window.open('http://www.ecomed.org.uk/wp-content/uploads/2011/09/3-tomljenovic.pdf'); return false;">Here</a> is an example of a paper that describes how vaccine manufactures and medical &lsquo;experts&rsquo; with drug industry connections have been aware of the multiple dangers associated with vaccinations for over 30 years. We&rsquo;d also like to present medical research that indicates the many dangers associated with vaccines, and have done this on multiple occasions. We do this because the safety of vaccinations is commonly pushed by the mainstream media, without ever mentioning or citing the abundant medical research that should also be taken into consideration when discussing vaccinations. Please keep in mind that there is evidence on both sides. At the same time, some of the evidence on the side that negates a positive outlook on vaccination has been labelled fraudulent, but then again many haven&rsquo;t.</p>
        <p>The vaccine-autism debate has been going on for years. It has been a tale of shifting beliefs as child vaccination rates remain high. On February 1998, Andrew Wakefield, a British gastroenterologist and his colleagues published a paper that supposedly linked Autism to Vaccines<a href="http://cid.oxfordjournals.org/content/48/4/456.full" onclick="javascript:window.open('http://cid.oxfordjournals.org/content/48/4/456.full'); return false;">(5)</a>. More specifically, he claimed that the MMR vaccine was responsible for intestinal inflammation that led to translocation of usually non-permeable peptides to the bloodstream and, subsequently, to the brain, where they affected development(5). His work was unpublished, and he lost his medical license despite the fact multiple studies seem to support Andrew Wakefield&rsquo;s work. He has been labelled a fraud by the mainstream medical world, some experts claim that his research and methods are weak and based on very little evidence. Dr Wakefield&rsquo;s research will NOT be used in this article.</p>
        <p>At the same time I must mention that multiple studies from around the world have concluded that there is no link between Autism and the MMR Vaccine(5). It can become quite confusing a subject given that we have multiple medical studies contradicting each other. Was Dr. Wakefield exposing something that the medical industry did not want you to know? It is known that vaccine manufacturers suppress harmful data regarding their product, as mentioned and illustrated earlier in the article. Regardless of the MMR vaccine and autism debate, there are still a number of studies that link vaccines to a possible autism connection. Please keep in mind that multiple courts worldwide have ruled in favour of vaccines causing autism, brain damage and other complications (6)(7), that include the MMR vaccine.</p>
        <p>Here is a great video narrated by <a href="http://www.collective-evolution.com/2012/09/07/rob-schneider-speaks-out-against-vaccines/" onclick="javascript:window.open('http://www.collective-evolution.com/2012/09/07/rob-schneider-speaks-out-against-vaccines/'); return false;">Rob Schneider</a> outlining the vaccine-autsim link. Below that you will find a list of 22 medical studies that show possible connections to vaccines and autism. Please keep in mind that we&rsquo;ve only presented 22 studies here, there are many more published papers that document the link. Hopefully this inspires you to further your research on the subject. Also keep in mind that Autism is only one of the multiple shown consequences of vaccine administration, as they have been linked to a number of other ailments.</p>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/6S1-LgYyjQg" frameborder="0" allowfullscreen></iframe>
        <p>1. <a href="http://www.ncbi.nlm.nih.gov/pubmed/21058170" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/21058170'); return false;">A study published in the journal <em>Annals of Epidemiology</em></a> has shown that giving the Hepatitis B vaccine to newborn baby boys could triple the risk of developing an autism spectrum disorder compared to boys who were not vaccinated as neonates. The research was conducted at Stony Brook University Medical Center, NY.</p>
        <p>2. <a href="http://omsj.org/reports/tomljenovic%202011.pdf" onclick="javascript:window.open('http://omsj.org/reports/tomljenovic%202011.pdf'); return false;">A study published in the </a><a href="http://omsj.org/reports/tomljenovic%202011.pdf" onclick="javascript:window.open('http://omsj.org/reports/tomljenovic%202011.pdf'); return false;"><em>Journal of Inorganic Biochemistry</em> </a>by researchers at the Neural Dynamics Group, Department of Ophthalmology and Visual Sciences at the University of British Columbia determined that Aluminum, a highly neurotoxic metal and the most commonly used vaccine adjuvant may be a significant contributing factor to the rising prevalence of ASD in the Western World. They showed that the correlation between ASD prevalence and the Aluminum adjuvant exposure appears to be the highest at 3-4 months of age. The studies also show that children from countries with the highest ASD appear to have a much higher exposure to Aluminum from vaccines. The study points out that several prominent milestones of brain development coincide with major vaccination periods for infants. These include the onset of synaptogenesis (birth), maximal growth velocity of the hippocampus and the onset of amygdala maturation. Furthermore, major developmental transition in many bio-behavioural symptoms such as sleep, temperature regulation, respiration and brain wave patterns, all of which are regulated by the neuroendocrine network. Many of these aspects of brain function are known to be impaired in autism, such as sleeping and brain wave patterns.</p>
        <p>According to the FDA, vaccines represent a special category of drugs as they are generally given to healthy individuals. Further according to the FDA, &ldquo;this places significant emphasis on their vaccine safety&rdquo;. While the FDA does set an upper limit for Aluminum in vaccines at no more that 850/mg/dose, it is important to note that this amount was selected empirically from data showing that Aluminum in such amounts enhanced the antigenicity of the vaccine, rather than from existing safety. Given that the scientific evidence appears to indicate that vaccine safety is not as firmly established as often believed, it would seem ill advised to exclude paediatric vaccinations as a possible cause of adverse long-term neurodevelopment outcomes , including those associated with autism.</p>
        <p>3. <a href="http://www.ncbi.nlm.nih.gov/pubmed/21623535" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/21623535'); return false;">A study published in the</a><a href="http://www.ncbi.nlm.nih.gov/pubmed/21623535" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/21623535'); return false;"> <em>Journal </em></a><em>of Toxicology and Environmental Health</em>, Part A: Current Issues by the Department of Economics and Finance at the University of New York shows how researchers suspect one or more environmental triggers are needed to develop autism, regardless of whether individuals have a genetic predisposition or not. They determined that one of those triggers might be the &ldquo;battery of vaccinations that young children receive.&rdquo; Researchers found a positive and statistically significant relationship between autism and vaccinations. They determined that the higher the proportion of children receiving recommended vaccinations, the higher the prevalence of autism. A 1 % increase in vaccination was associated with an additional 680 children having autism. The results suggest that vaccines may be linked to autism and encourages more in depth study before continually administering these vaccines.</p>
        <p>4. <a href="http://www.hindawi.com/journals/jt/2013/801517/" onclick="javascript:window.open('http://www.hindawi.com/journals/jt/2013/801517/'); return false;">A study published in the </a><a href="http://www.hindawi.com/journals/jt/2013/801517/" onclick="javascript:window.open('http://www.hindawi.com/journals/jt/2013/801517/'); return false;"><em>Journal of Toxicology</em></a> by the Department of Neurosurgery at The Methodist Neurological Institute in Houston has shown that ASD is a disorder caused by a problem in brain development. They looked at B-cells and their sensitivity levels to thimerosal, a commonly used additive in many vaccines. They determined that ASD patients have a heightened sensitivity to thimerosal which would restrict cell proliferation that is typically found after vaccination. The research shows that individuals who have this hypersensitivity to thimerosal could make them highly susceptible to toxins like thimerosal, and that individuals with a mild mitochondrial defect may be affected by thimerosal. The fact that ASD patients&rsquo; B cells exhibit hypersensitivity to thimerosal tells us something.</p>
        <p>5. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12145534" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/12145534'); return false;">A study published in the <em>Journal of Biomedical Sciences</em></a> determined that the autoimmunity to the central nervous system may play a causal role in autism. Researchers discovered that because many autistic children harbour elevated levels of measles antibodies, they should conduct a serological study of measles-mumps-rubella (MMR) and <a href="http://www.mybiosource.com/prods/ELISA-Kit/Human/myelin-basic-protein/MBP/datasheet.php?products_id=700083" onclick="javascript:window.open('http://www.mybiosource.com/prods/ELISA-Kit/Human/myelin-basic-protein/MBP/datasheet.php?products_id=700083'); return false;">myelin basic protein</a> (MBP) autoantibodies. They used serum samples of 125 autistic children and 92 controlled children. Their analysis showed a significant increase in the level of MMR antibodies in autistic children. The study concludes that the autistic children had an inappropriate or abnormal antibody response to MMR. The study determined that autism could be a result from an atypical measles infection that produces neurological symptoms in some children. The source of this virus could be a variant of MV, or it could be the MMR vaccine.</p>
        <p>6. <a href="http://www.collective-evolution.com/2013/09/12/22-medical-studies-that-show-vaccines-can-cause-autism/Study%20published%20in%20the%20Annals%20of%20Clinical%20Psychiatry" onclick="javascript:window.open('http://www.collective-evolution.com/2013/09/12/22-medical-studies-that-show-vaccines-can-cause-autism/Study%20published%20in%20the%20Annals%20of%20Clinical%20Psychiatry'); return false;">Study published in the </a><a href="http://www.collective-evolution.com/2013/09/12/22-medical-studies-that-show-vaccines-can-cause-autism/Study%20published%20in%20the%20Annals%20of%20Clinical%20Psychiatry" onclick="javascript:window.open('http://www.collective-evolution.com/2013/09/12/22-medical-studies-that-show-vaccines-can-cause-autism/Study%20published%20in%20the%20Annals%20of%20Clinical%20Psychiatry'); return false;"><em>Annals of Clinical Psychiatry </em></a>suggests that Autism is likely triggered by a virus, and that measles virus (MV and/or MMR vaccine) might be a very good candidate. It supports the hypothesis that a virus-dincued autoimmune response may play a causal role in autism.</p>
        <p>7. <a href="http://ajcn.nutrition.org/content/80/6/1611.full" onclick="javascript:window.open('http://ajcn.nutrition.org/content/80/6/1611.full'); return false;">A study published in the </a><a href="http://ajcn.nutrition.org/content/80/6/1611.full" onclick="javascript:window.open('http://ajcn.nutrition.org/content/80/6/1611.full'); return false;"><em>American Journal of Clinical Nutrition</em></a> determined that an increased vulnerability to oxidative stress and decreased capacity for methylation may contribute to the development and clinical manifestation of autism. It&rsquo;s well known that viral infections cause increased oxidative stress. <a href="http://www.ncbi.nlm.nih.gov/pubmed/11895129" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/11895129'); return false;">Research suggests</a> that metals, including those found in many vaccines are directly involved in increasing oxidative stress.</p>
        <p>8. <a href="http://www.ncbi.nlm.nih.gov/pubmed/14745455" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/14745455'); return false;">A study published by the Department of Pharmaceutical Sciences</a>at Northeastern University, Boston determined that a novel growth factor signalling pathway that regulates methionine synthase(MS) activity and thereby modulates methylation reactions. The potent inhibition of this pathway by ethanol, lead, mercury, aluminum and thimerosal suggests that it may be an important target of neurodevelopmental toxins. You can read more about this <a href="http://legacy.autism.com/medical/research/deth.htm" onclick="javascript:window.open('http://legacy.autism.com/medical/research/deth.htm'); return false;">here</a>, and <a href="https://imfar.confex.com/imfar/2010/webprogram/Paper5280.html" onclick="javascript:window.open('https://imfar.confex.com/imfar/2010/webprogram/Paper5280.html'); return false;">here</a>. You can read more about the MS/autism link <a href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0056927" onclick="javascript:window.open('http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0056927'); return false;">here</a></p>
        <p>9. <a href="http://jcn.sagepub.com/content/22/11/1308.abstract" onclick="javascript:window.open('http://jcn.sagepub.com/content/22/11/1308.abstract'); return false;">A study published in the <em>Journal of Child Neurology</em></a> examined the question of what is leading to the apparent increase in autism. They expressed that if there is any link between autism and mercury, it is crucial that the first reports of the question are not falsely stating that no link occurs. Researchers determined that a significant relation does exist between the blood levels of mercury and the diagnosis of an autism spectrum disorder.</p>
        <p>10. <a href="http://jcn.sagepub.com/content/21/2/170.abstract" onclick="javascript:window.open('http://jcn.sagepub.com/content/21/2/170.abstract'); return false;">A study published in the</a><a href="http://jcn.sagepub.com/content/21/2/170.abstract" onclick="javascript:window.open('http://jcn.sagepub.com/content/21/2/170.abstract'); return false;"> <em>Journal of Child Neurology</em></a> noted that autistic spectrum disorders can be associated with mitochondrial dysfunction. Researchers determined that children who have mitochondrial-related dysfunctional cellular energy metabolism might be more prone to undergo autistic regression between 18 and 30 months of age if they also have infections or immunizations at the same time.</p>
        <p>11. <a href="http://www.ncbi.nlm.nih.gov/pubmed/16151044" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/16151044'); return false;">A study conducted by Massachusetts General Hospital</a> at the Centre for Morphometric Analysis by the department of Paediatric Neurology illustrates how autistic brains have a growth spurt shortly after birth and then slow in growth a few short years later. Researchers have determined that neuroinflammation appears to be present in autistic brain tissue from childhood through adulthood. The study excerpt reads:</p>
        <blockquote>
          <p>Oxidative stress, brain inflammation and microgliosis have been much documented in association with toxic exposures including various heavy metals. The awareness that the brain as well as medical conditions of children with autism may be conditioned by chronic biomedical abnormalities such as inflammation opens the possibility that meaningful biomedical interventions may be possible well past the window of maximal neuroplasticity in early childhood because the basis for assuming that all deficits can be attributed to fixed early developmental alterations in net.</p>
        </blockquote>
        <p>12, <a href="http://www.ncbi.nlm.nih.gov/pubmed/15527868" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/15527868'); return false;">A study conducted by the Department of Paediatrics at the University of Arkansas</a>determined that thimerosal-induced cytotoxicity was associated with the depletion of intracellular glutathione (GSH) in both cell lines. The study outlines how many vaccines have been neurotoxic, especially to the developing brain. Depletion of GSH is commonly associated with autism. Although thimerosal has been removed from most children&rsquo;s vaccines, it is still present in flu vaccines given to pregnant women, the elderly and to children in developing countries.</p>
        <p>13. <a href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0068444" onclick="javascript:window.open('http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0068444'); return false;">A study published in the </a><a href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0068444" onclick="javascript:window.open('http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0068444'); return false;">Public Library of Science (PLOS)</a> determined that elevation in peripheral oxidative stress is consistent with, and may contribute to more severe functional impairments in the ASD group. We know that oxidative stress is triggered by heavy metals, like the ones contained in multiple vaccines.</p>
        <p>14. <a href="http://www.ncbi.nlm.nih.gov/pubmed/16338635" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/16338635'); return false;">A study conducted by the University of Texas Health Science Center</a> by the Department of Family and Community Medicine determined that for each 1,000 Ib of environmentally released mercury, there was a 43% increase in the rate of special education services and a 61% increase in the rate of autism. Researchers emphasized that further research was needed regarding the association between environmentally released mercury and developmental disorders such as autism.</p>
        <p>15. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12933322" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/12933322'); return false;">A study published in the <em>International Journal of Toxicology</em></a> determined that in light of the biological plausibility of mercury&rsquo;s role in neurodevelopment disorders, the present study provides further insight into one possible mechanism by which early mercury exposures could increase the risk of autism.</p>
        <p>16. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17454560" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/17454560'); return false;">A study published in the </a><a href="http://www.ncbi.nlm.nih.gov/pubmed/17454560" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/17454560'); return false;"><em>Journal of Toxicology and Environmental Health</em></a> determined that mercury exposure can induce immune, sensory, neurological, motor and behavioural dysfunctions similar to traits defining or associated with ASDs. Based upon differential diagnoses, 8 of 9 patients examined were exposed to significant mercury from Thimerosal-containing vaccine preparations during their fetal/infant developmental periods. These previously normal developing children suffered mercury encephalopathies that manifested with clinical symptoms consistent with regressive ASDs. Evidence for mercury intoxication should be considered in the differential diagnosis as contributing to some regressive ASDs.</p>
        <p>17.<a href="http://civileats.com/wp-content/uploads/2009/01/palmer2008.pdf" onclick="javascript:window.open('http://civileats.com/wp-content/uploads/2009/01/palmer2008.pdf'); return false;"> A study published by the US National Library of Medicine </a>conducted by the University of Texas Health Science Centre suspected that persistent low-dose exposures to various environmental toxicants including mercury, that occur during critical windows of neural development among genetically susceptible children, may increase the risk for developmental disorders such as autism.</p>
        <p>18.<a href="http://www.ane.pl/pdf/7020.pdf" onclick="javascript:window.open('http://www.ane.pl/pdf/7020.pdf'); return false;"> A study conducted by the Department of Obstetrics and Gynaecology</a> at University of Pittsburgh&rsquo;s School of Medicine showed that Macaques are commonly used in pre-clinical vaccine safety testing. Collective Evolution does not support animals testing, we feel there is a large amount of evidence and research that already indicated the links to vaccines in which some animals have been used to illustrate. The objective of this study was to compare early infant cognition and behaviour with amygdala size and opioid binding in rhesus macaques receiving the recommended childhood vaccines. The animal model, which examines for the first time, behavioural, functional and neuromorphometric consequences of the childhood vaccine regimen, mimics certain neurological abnormalities of autism. These findings raise important safety issues while providing a potential model for examining aspects of causation and disease pathogenesis in acquired disorders of behaviour and development.</p>
        <p>19. <a href="http://www.ncbi.nlm.nih.gov/pubmed/18482737" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/18482737'); return false;">A study conducted by The George Washington University School of Public Health</a> from the Department of Epidemiology and Biostatistics determined that significantly increased rate ratios were observed for autism and autism spectrum disorders as a result of exposure to mercury from Thimerosal-containing vaccines.</p>
        <p>20. <a href="http://www.ncbi.nlm.nih.gov/pubmed/19357975" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pubmed/19357975'); return false;">A study published in the journal <em>Cell Biology and Toxicology</em></a> by Kinki University in Osaka, Japan determined that in combination with the brain pathology observed in patients diagnosed with autism, the present study helps to support the possible biological plausibility for how low-dose exposure to mercury from thimerosal-containing vaccines may be associated with autism.</p>
        <p>21. <a href="http://labmed.ascpjournals.org/content/33/9/708.full.pdf" onclick="javascript:window.open('http://labmed.ascpjournals.org/content/33/9/708.full.pdf'); return false;">A study published by the</a><a href="http://labmed.ascpjournals.org/content/33/9/708.full.pdf" onclick="javascript:window.open('http://labmed.ascpjournals.org/content/33/9/708.full.pdf'); return false;"> journal <em>Lab Medicine</em></a> determined that vaccinations may be one of the triggers for autism. Researchers discovered that substantial data demonstrates immune abnormality in many autistic children consistent with impaired resistance to infection, activation of inflammatory responses and autoimmunity. Impaired resistance may predispose to vaccine injury in autism.</p>
        <p>22. <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3264864/?tool=pubmed" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3264864/?tool=pubmed'); return false;">A study published in the journal </a><em><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3264864/?tool=pubmed" onclick="javascript:window.open('http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3264864/?tool=pubmed'); return false;">Neurochemical Research</a> </em>determined that since excessive accumulation of extracellular glutamate is linked with excitotoxicity, data implies that neonatal exposure to thimerosal-containing vaccines might induce excitotoxic brain injuries, leading to neurodevelopmental disorders.</p>
        </div>
      </div>

    </div><!-- /.container -->





    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="../js/bootstrap.min.js"></script>
  </body>
</html>